(function()openSys={
[1]={startLv=4,giveItem={}},
[2]={startLv=8,giveItem={}},
[3]={startLv=10,giveItem={}},
[4]={startLv=20,giveItem={}},
[5]={startLv=25,giveItem={}},
[6]={startLv=30,giveItem={}},
[7]={startLv=40,giveItem={}},
[8]={startLv=45,giveItem={}},
[9]={startLv=50,giveItem={}}}end)();
